Capstone project: Tunisia Covid Tracker
Taher-web-dev/Tunisa-Covid-Live-App pull request #1
Opened 2021-12-23 13:08 UTC by Taher-web-dev

In this project , I have created a mobile web application to track Covid situation in my country Tunisia. This application display the main indicators and metrics allow to grasp the real situation in a country, it ensure also the running of all the features required in this capstone project. Therefore you find in this branch the following changes :100: 
- Home page : 
     * When the page loads, the webapp shows the list of main indicators  that could give a general idea about the country Covid spread situation. :+1: 
    * Along with the category name, we display some numeric values per category that come from the API. :+1: 
    * When the user clicks (or taps) on a category item, the application navigates to the details page. :+1: 
- Details page:
    * In the details page, the webapp retrieves data from the API to show detailed data in the category. :+1: 
    * When the user clicks on the "Back" button (<), the user navigates to the home page. :+1: 
 
You can watch this video presentation of my project :
https://www.loom.com/share/cf1b20cd49504fd490a3d4157f398d42

2021-12-23 13:28 UTC, rukundoeric requested changes
Hi @Taher-web-dev, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] You only have two test cases and you did not test other components except home. Kindly test other components and make sure to not only test `snapshots`.
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-23 13:28 UTC, rukundoeric commented on src/App.js
> +function App() {
- [ ] <b>REQUIRED:<b/> Prefer using ES6 arrow function. Actually, there is nothing wrong with ES5 functions syntax but it is mandatory to use es6 features in the javascript module. besides, Arrow functions provide a simplified structure, allowing for a more concise way to write function expressions. which makes them better than ES5 functions(function declarations). Here is the syntax of an ES6 arrow function...
```javascript
  const functionName = () => {
     // code here
  }
```

2021-12-23 14:01 UTC, rukundoeric requested changes
Hi @Taher-web-dev, 

_Great job so far 👏 💯 👍. You've done well implementing some of the requested changes. However, there are still some which aren't addressed yet. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 
  - Addressed some of the issues raised from the previous review. 💯 

## Required Changes ♻️
  - [ ] As I mentioned in the previous review, You only have two test cases and you did not test other components except home. Kindly test other components and make sure to not only test snapshots.
  ![Screen Shot 2021-12-23 at 15 46 06](https://user-images.githubusercontent.com/45217364/147250935-19b089ea-2b0a-4132-b257-c1f80b2a1304.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
  
  - N/A 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-23 17:02 UTC, D4nielJ requested changes
## Hello @Taher-web-dev, 

Great work on making the changes requested by the previous reviewer(s) 👏

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Happy coding and stay awesome! 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 17:02 UTC, D4nielJ commented on src/__test__/ChartOPenCases.test.js
> +    expect(tree.toJSON()).toMatchSnapshot();
- [ ] Good job implementing new tests, however, as the previous code reviewer mentioned. It's a good idea to not only implement snapshots, as this only tests for integration reliability but not functionality. Let's also implement some unit tests for functionality.

> App has **unit tests** for several components of the app and some **pure functions** in Redux code.

2021-12-23 17:02 UTC, D4nielJ commented on src/components/Recovered/ChartRecoveredMonth.js
> +  }
For instance, you might want to test if you are getting the correct information of `newCasesData` every time.

2021-12-23 17:02 UTC, D4nielJ commented on src/components/Recovered/Recovered.js
> +  }
Or you might want to make sure that the calculation of the growingRate it's correct. I think there are plenty of tests that you can implement. So please implement some, it's a good practice and very valuable in almost every company.

2021-12-23 17:02 UTC, D4nielJ commented on src/index.js
> +      <App />
[OPTIONAL] Also, I'm sorry my partner did not mention it, but there is also a requirement to implement a stateless filter component that allows the user to filter data from the app somehow.

> Uses a Filter stateless component to filter data retrieved from the API.

I highly encourage you to do this, as it's a good exercise and part of the requirements.

2021-12-24 00:08 UTC, rukundoeric approved these changes
Hi @Taher-web-dev,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-24 08:17 UTC, merged